"""add msa context fields

Revision ID: c2b1f3d4e5a6
Revises: 998e1302e4e5
Create Date: 2025-10-07 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2b1f3d4e5a6"
down_revision = "998e1302e4e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("use_msa_context", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("msa_a3m_path", sa.String(), nullable=True))

    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("use_msa_context", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("msa_a3m_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.drop_column("msa_a3m_path")
        batch_op.drop_column("use_msa_context")

    with op.batch_alter_table("logits", schema=None) as batch_op:
        batch_op.drop_column("msa_a3m_path")
        batch_op.drop_column("use_msa_context")
    # ### end Alembic commands ###
